In [1]:
import pandas as pd

In [4]:
var = pd.DataFrame({"A": [1,2,3,4,5], 
                    "B": [5,7,8,9,0]})
var

   A  B
0  1  5
1  2  7
2  3  8
3  4  9
4  5  0

In [5]:
var.insert(1, "python", var["A"])
var

   A  python  B
0  1       1  5
1  2       2  7
2  3       3  8
3  4       4  9
4  5       5  0

In [10]:
var.insert(3, "python2", [1,2,3,4,5])
var

   A  python1  python  python2  B
0  1        1       1        1  5
1  2        2       2        2  7
2  3        3       3        3  8
3  4        4       4        4  9
4  5        5       5        5  0

###DELETE

In [11]:
var1 = var.pop("B")
var1

0    5
1    7
2    8
3    9
4    0
Name: B, dtype: int64

In [12]:
var

   A  python1  python  python2
0  1        1       1        1
1  2        2       2        2
2  3        3       3        3
3  4        4       4        4
4  5        5       5        5

In [21]:
var.pop("python")
var

   python1  python2
0        1        1
1        2        2
2        3        3
3        4        4
4        5        5